netbox_lcm/urls.py
from django.urls import path

from netbox.views.generic import ObjectChangeLogView
from . import views
from netbox_lcm.models import (
    DeviceBackupPolicy,
    DeviceBackupResult,
    HardwareLifecycle,
    HardwareLifecyclePlan,
    SupportContract,
    License,
    LicenseAssignment,
    SupportContractAssignment,
    SupportSKU,
    Vendor,
    )

urlpatterns = [
    path('hardware/', views.HardwareLifecycleListView.as_view(), name='hardwarelifecycle_list'),
    path('hardware/add', views.HardwareLifecycleEditView.as_view(), name='hardwarelifecycle_add'),
    path('hardware/edit', views.HardwareLifecycleBulkEditView.as_view(), name='hardwarelifecycle_bulk_edit'),
    path('hardware/delete', views.HardwareLifecycleBulkDeleteView.as_view(), name='hardwarelifecycle_bulk_delete'),
    path('hardware/<int:pk>', views.HardwareLifecycleView.as_view(), name='hardwarelifecycle'),
    path('hardware/<int:pk>/edit', views.HardwareLifecycleEditView.as_view(), name='hardwarelifecycle_edit'),
    path('hardware/<int:pk>/delete', views.HardwareLifecycleDeleteView.as_view(), name='hardwarelifecycle_delete'),
    path('hardware/<int:pk>/changelog', ObjectChangeLogView.as_view(), name='hardwarelifecycle_changelog', \
        kwargs={'model': HardwareLifecycle}),

    path('hardware-plan/', views.HardwareLifecyclePlanListView.as_view(), name='hardwarelifecycleplan_list'),
    path('hardware-plan/add', views.HardwareLifecyclePlanEditView.as_view(), name='hardwarelifecycleplan_add'),
    path('hardware-plan/edit', views.HardwareLifecyclePlanBulkEditView.as_view(), name='hardwarelifecycleplan_bulk_edit'),
    path('hardware-plan/delete', views.HardwareLifecyclePlanBulkDeleteView.as_view(), name='hardwarelifecycleplan_bulk_delete'),
    path('hardware-plan/<int:pk>', views.HardwareLifecyclePlanView.as_view(), name='hardwarelifecycleplan'),
    path('hardware-plan/<int:pk>/edit', views.HardwareLifecyclePlanEditView.as_view(), name='hardwarelifecycleplan_edit'),
    path('hardware-plan/<int:pk>/delete', views.HardwareLifecyclePlanDeleteView.as_view(), name='hardwarelifecycleplan_delete'),
    path('hardware-plan/<int:pk>/changelog', ObjectChangeLogView.as_view(), name='hardwarelifecycleplan_changelog', \
         kwargs={'model': HardwareLifecyclePlan}),

    path('vendors/', views.VendorListView.as_view(), name='vendor_list'),
    path('vendors/add', views.VendorEditView.as_view(), name='vendor_add'),
    path('vendors/edit', views.VendorBulkEditView.as_view(), name='vendor_bulk_edit'),
    path('vendors/delete', views.VendorBulkDeleteView.as_view(), name='vendor_bulk_delete'),
    path('vendors/<int:pk>', views.VendorView.as_view(), name='vendor'),
    path('vendors/<int:pk>/edit', views.VendorEditView.as_view(), name='vendor_edit'),
    path('vendors/<int:pk>/delete', views.VendorDeleteView.as_view(), name='vendor_delete'),
    path('vendors/<int:pk>/changelog', ObjectChangeLogView.as_view(), \
        name='vendor_changelog', kwargs={'model': Vendor}),

    path('contracts/', views.SupportContractListView.as_view(), name='supportcontract_list'),
    path('contracts/add', views.SupportContractEditView.as_view(), name='supportcontract_add'),
    path('contracts/edit', views.SupportContractBulkEditView.as_view(), name='supportcontract_bulk_edit'),
    path('contracts/delete', views.SupportContractBulkDeleteView.as_view(), name='supportcontract_bulk_delete'),
    path('contracts/<int:pk>', views.SupportContractView.as_view(), name='supportcontract'),
    path('contracts/<int:pk>/devices', views.SupportContractAssignmentsView.as_view(), name='supportcontract_assignments'),
    path('contracts/<int:pk>/edit', views.SupportContractEditView.as_view(), name='supportcontract_edit'),
    path('contracts/<int:pk>/delete', views.SupportContractDeleteView.as_view(), name='supportcontract_delete'),
    path('contracts/<int:pk>/changelog', ObjectChangeLogView.as_view(), \
        name='supportcontract_changelog', kwargs={'model': SupportContract}),

    path('contract-assignment/', views.SupportContractAssignmentListView.as_view(), \
        name='supportcontractassignment_list'),
    path('contract-assignment/add', views.SupportContractAssignmentEditView.as_view(), \
        name='supportcontractassignment_add'),
    path('contract-assignment/edit/', views.SupportContractAssignmentBulkEditView.as_view(), \
        name='supportcontractassignment_bulk_edit'),
    path('contract-assignment/delete/', views.SupportContractAssignmentBulkDeleteView.as_view(), \
        name='supportcontractassignment_bulk_delete'),
    path('contract-assignment/<int:pk>', views.SupportContractAssignmentView.as_view(), \
        name='supportcontractassignment'),
    path('contract-assignment/<int:pk>/edit', views.SupportContractAssignmentEditView.as_view(), \
        name='supportcontractassignment_edit'),
    path('contract-assignment/<int:pk>/delete', views.SupportContractAssignmentDeleteView.as_view(), \
        name='supportcontractassignment_delete'),
    path('contract-assignment/<int:pk>/changelog', ObjectChangeLogView.as_view(), \
        name='supportcontractassignment_changelog', kwargs={'model': SupportContractAssignment}),

    path('license/', views.LicenseListView.as_view(), name='license_list'),
    path('license/add', views.LicenseEditView.as_view(), name='license_add'),
    path('license/edit', views.LicenseBulkEditView.as_view(), name='license_bulk_edit'),
    path('license/delete', views.LicenseBulkDeleteView.as_view(), name='license_bulk_delete'),
    path('license/<int:pk>', views.LicenseView.as_view(), name='license'),
    path('license/<int:pk>/assignments', views.LicenseAssignmentsView.as_view(), name='license_assignments'),
    path('license/<int:pk>/edit', views.LicenseEditView.as_view(), name='license_edit'),
    path('license/<int:pk>/delete', views.LicenseDeleteView.as_view(), name='license_delete'),
    path('license/<int:pk>/changelog', ObjectChangeLogView.as_view(), name='license_changelog', \
         kwargs={'model': License}),

    path('sku/', views.SupportSKUListView.as_view(), name='supportsku_list'),
    path('sku/add', views.SupportSKUEditView.as_view(), name='supportsku_add'),
    path('sku/edit', views.SupportSKUBulkEditView.as_view(), name='supportsku_bulk_edit'),
    path('sku/delete', views.SupportSKUBulkDeleteView.as_view(), name='supportsku_bulk_delete'),
    path('sku/<int:pk>', views.SupportSKUView.as_view(), name='supportsku'),
    path('sku/<int:pk>/edit', views.SupportSKUEditView.as_view(), name='supportsku_edit'),
    path('sku/<int:pk>/delete', views.SupportSKUDeleteView.as_view(), name='supportsku_delete'),
    path('sku/<int:pk>/changelog', ObjectChangeLogView.as_view(), name='supportsku_changelog', \
         kwargs={'model': SupportSKU}),

    path('license-assignment/', views.LicenseAssignmentListView.as_view(), name='licenseassignment_list'),
    path('license-assignment/add', views.LicenseAssignmentEditView.as_view(), name='licenseassignment_add'),
    path('license-assignment/edit', views.LicenseAssignmentBulkEditView.as_view(), name='licenseassignment_bulk_edit'),
    path('license-assignment/delete/', views.LicenseAssignmentBulkDeleteView.as_view(), name='licenseassignment_bulk_delete'),
    path('license-assignment/<int:pk>', views.LicenseAssignmentView.as_view(), name='licenseassignment'),
    path('license-assignment/<int:pk>/edit', views.LicenseAssignmentEditView.as_view(), name='licenseassignment_edit'),
    path('license-assignment/<int:pk>/delete', views.LicenseAssignmentDeleteView.as_view(), name='licenseassignment_delete'),
    path('license-assignment/<int:pk>/changelog', ObjectChangeLogView.as_view(), \
        name='licenseassignment_changelog', kwargs={'model': LicenseAssignment}),
    
    path('device-backup-policy/', views.DeviceBackupPolicyListView.as_view(), name='devicebackuppolicy_list'),
    path('device-backup-policy/add', views.DeviceBackupPolicyEditView.as_view(), name='devicebackuppolicy_add'),
    path('device-backup-policy/edit', views.DeviceBackupPolicyBulkEditView.as_view(), name='devicebackuppolicy_bulk_edit'),
    path('device-backup-policy/delete/', views.DeviceBackupPolicyBulkDeleteView.as_view(), name='devicebackuppolicy_bulk_delete'),
    path('device-backup-policy/<int:pk>', views.DeviceBackupPolicyView.as_view(), name='devicebackuppolicy'),
    path('device-backup-policy/<int:pk>/edit', views.DeviceBackupPolicyEditView.as_view(), name='devicebackuppolicy_edit'),
    path('device-backup-policy/<int:pk>/delete', views.DeviceBackupPolicyDeleteView.as_view(), name='devicebackuppolicy_delete'),
    path('device-backup-policy/<int:pk>/changelog', ObjectChangeLogView.as_view(), \
        name='devicebackuppolicy_changelog', kwargs={'model': DeviceBackupPolicy}),

    # Device Lifecycle Vew - Read Only List
    path('devices/', views.DeviceLifecycleListView.as_view(), name='devicelifecycle_list'),
]

netbox_lcm/models/contract.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.db.models.functions import Lower
from django.urls import reverse
from django.utils.translation import gettext as _

from netbox_lcm.choices import SupportCoverageStatusChoices
from dcim.choices import DeviceStatusChoices
from netbox.models import PrimaryModel


__all__ = (
    'Vendor',
    'SupportSKU',
    'SupportContract',
    'SupportContractAssignment',
)


class Vendor(PrimaryModel):
    name = models.CharField(max_length=100)

    clone_fields = ()
    prerequisite_models = ()

    class Meta:
        ordering = ['name']
        constraints = (
            models.UniqueConstraint(
                Lower('name'),
                name='%(app_label)s_%(class)s_unique_name',
                violation_error_message="Vendor must be unique."
            ),
        )

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('plugins:netbox_lcm:vendor', args=[self.pk])


class SupportSKU(PrimaryModel):
    manufacturer = models.ForeignKey(
        to='dcim.Manufacturer',
        on_delete=models.CASCADE,
        related_name='skus',
    )
    sku = models.CharField(max_length=100)

    clone_fields = (
        'manufacturer',
    )
    prerequisite_models = (
        'dcim.Manufacturer',
    )

    class Meta:
        ordering = ['manufacturer', 'sku']
        constraints = (
            models.UniqueConstraint(
                'manufacturer', Lower('sku'),
                name='%(app_label)s_%(class)s_unique_manufacturer_sku',
                violation_error_message="SKU must be unique per manufacturer."
            ),
        )

    def __str__(self):
        return f'{self.sku}'

    def get_absolute_url(self):
        return reverse('plugins:netbox_lcm:supportsku', args=[self.pk])


class SupportContract(PrimaryModel):
    vendor = models.ForeignKey(
        to='netbox_lcm.Vendor',
        on_delete=models.SET_NULL,
        related_name='contracts',
        null=True,
        blank=True,
    )
    contract_id = models.CharField(max_length=100)
    start = models.DateField(null=True, blank=True)
    renewal = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)

    clone_fields = (
        'vendor', 'start', 'renewal', 'end'
    )
    prerequisite_models = (
        'netbox_lcm.Vendor',
    )

    class Meta:
        ordering = ['contract_id']
        constraints = (
            models.UniqueConstraint(
                'vendor', Lower('contract_id'),
                name='%(app_label)s_%(class)s_unique_vendor_contract_id',
                violation_error_message="Contract must be unique per vendor."
            ),
        )

    def __str__(self):
        return f'{self.contract_id}'

    def get_absolute_url(self):
        return reverse('plugins:netbox_lcm:supportcontract', args=[self.pk])


class SupportContractAssignment(PrimaryModel):
    contract = models.ForeignKey(
        to='netbox_lcm.SupportContract',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='assignments',
    )
    sku = models.ForeignKey(
        to='netbox_lcm.SupportSKU',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='assignments',
    )
    device = models.ForeignKey(
        to='dcim.Device',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='contracts',
    )
    license = models.ForeignKey(
        to='netbox_lcm.LicenseAssignment',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='contracts',
    )
    end = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('End Date'),
        help_text=_('A unique end date varying from the contract')
    )
    support_coverage_status = models.CharField(
        max_length=32,
        choices=SupportCoverageStatusChoices,
        blank=True,
        help_text=_("Support Coverage Status")
    )

    clone_fields = (
        'contract', 'sku', 'end',
    )
    prerequisite_models = (
        'netbox_lcm.SupportContract',
        'netbox_lcm.SupportSKU',
        'netbox_lcm.License',
        'dcim.Device',
    )

    class Meta:
        ordering = ['contract', 'device', 'license']
        constraints = ()

    def __str__(self):
        if self.license and self.device:
            return f'{self.device} ({self.license}): {self.contract.contract_id if self.contract else self.get_support_coverage_status_display()}'
        return f'{self.device}: {self.contract.contract_id if self.contract else self.get_support_coverage_status_display()}'

    def get_absolute_url(self):
        return reverse('plugins:netbox_lcm:supportcontractassignment', args=[self.pk])

    @property
    def end_date(self):
        if self.end:
            return self.end
        return self.contract.end

    def get_device_status_color(self):
        if self.device is None:
            return
        return DeviceStatusChoices.colors.get(self.device.status)

    def get_support_coverage_status_color(self):
        if self.device is None:
            return
        return SupportCoverageStatusChoices.colors.get(self.support_coverage_status)

    @property
    def assignment_type(self):
        if self.license:
            return 'license'
        else:
            return 'device'
    

    def clean(self):
        if self.contract:
            if not self.support_coverage_status == SupportCoverageStatusChoices.VENDOR_CONTRACT_ATTACHED:
                raise ValidationError({
                    'support_coverage_status': _('Contract can only be specified when "Supported - Vendor Contract Attached" is selected.')
                })
            else:
                self.support_coverage_status = SupportCoverageStatusChoices.VENDOR_CONTRACT_ATTACHED
        elif not self.contract:
            if not self.support_coverage_status:
                raise ValidationError({
                    'support_coverage_status': _('A reason must be specified if no contract is assigned.')
                })
            elif self.support_coverage_status == SupportCoverageStatusChoices.VENDOR_CONTRACT_ATTACHED:
                raise ValidationError({
                    'support_coverage_status': _('"Supported - Vendor Contract Attached" can only be used when a contract is assigned.')
                })

        # Uniqueness constraints
        qs = SupportContractAssignment.objects.filter(
            device=self.device, license=self.license, sku=self.sku
        ).exclude(pk=self.pk)

        if self.device and self.license and self.contract and qs.filter(contract=self.contract).exists():
            raise ValidationError('Device or License must be unique')
        elif self.device and not self.license and qs.filter(contract=self.contract).exists():
            raise ValidationError('Device must be unique')
        elif not self.device and self.license and qs.filter(contract=self.contract).exists():
            raise ValidationError('License must be unique')

netbox_lcm/api/views/license.py
from netbox.api.viewsets import NetBoxModelViewSet
from netbox_lcm.api.serializers import LicenseSerializer, LicenseAssignmentSerializer
from netbox_lcm.filtersets import LicenseAssignmentFilterSet, LicenseFilterSet
from netbox_lcm.models import License, LicenseAssignment


__all__ = (
    'LicenseViewSet',
    'LicenseAssignmentViewSet'
)


class LicenseViewSet(NetBoxModelViewSet):
    queryset = License.objects.all()
    serializer_class = LicenseSerializer
    filterset_class = LicenseFilterSet


class LicenseAssignmentViewSet(NetBoxModelViewSet):
    queryset = LicenseAssignment.objects.all()
    serializer_class = LicenseAssignmentSerializer
    filterset_class = LicenseAssignmentFilterSet

netbox_lcm/templates/netbox_lcm/devicelifecycle.html
{% extends 'generic/object_list.html' %}
{% load i18n %}


{% load render_table from django_tables2 %} 
{% block title %}{% trans "Device Lifecycle Information" %}{% endblock %}

{% block content %}
    {{ block.super }}
{% endblock content %}

netbox_lcm/templates/netbox_lcm/devicetypefamily.html
{% extends 'generic/object.html' %}
{% load i18n %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-12">
    <div class="card">
      <h5 class="card-header">{% trans "Device Type Family Details" %}</h5>
      <div class="card-body">
        <dl class="row">
          <dt class="col-sm-3">{% trans "Name" %}</dt>
          <dd class="col-sm-9">{{ object.name }}</dd>

          <dt class="col-sm-3">{% trans "Description" %}</dt>
          <dd class="col-sm-9">{{ object.description|linebreaksbr }}</dd>

          <dt class="col-sm-3">{% trans "Manufacturer" %}</dt>
          <dd class="col-sm-9">{{ object.manufacturer|linebreaksbr }}</dd>

          <dt class="col-sm-3">{% trans "Device Types" %}</dt>
          <dd class="col-sm-9">
            {% for dt in object.device_types.all %}
              <a href="{{ dt.get_absolute_url }}">{{ dt }}</a>{% if not forloop.last %}, {% endif %}
            {% empty %}
              <em>{% trans "None" %}</em>
            {% endfor %}
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>
{% endblock %}

netbox_lcm/templates/netbox_lcm/hardwarelifecycle_edit.html
{% extends 'generic/object_edit.html' %}
{% load form_helpers %}
{% load static %}

{% block form %}

    <div class="field-group my-5">
      <div class="row mb-2">
        <h5 class="offset-sm-3">Assignment</h5>
      </div>
      <div class="row mb-2">
        <div class="offset-sm-3">
          <ul class="nav nav-pills" role="tablist">
            <li role="presentation" class="nav-item">
              <button role="tab" type="button" id="device_tab" data-bs-toggle="tab" aria-controls="device-type" data-bs-target="#device-type" class="nav-link {% if not form.initial.module_type %}active{% endif %}">
                Device Type
              </button>
            </li>
            <li role="presentation" class="nav-item">
              <button role="tab" type="button" id="vm_tab" data-bs-toggle="tab" aria-controls="module-type" data-bs-target="#module-type" class="nav-link {% if form.initial.module_type %}active{% endif %}">
                Module Type
              </button>
            </li>
          </ul>
        </div>
      </div>
      <div class="tab-content p-0 border-0">
        <div class="tab-pane {% if not form.initial.module_type %}active{% endif %}" id="device-type" role="tabpanel" aria-labeledby="device_tab">
          {% render_field form.device_type %}
        </div>
        <div class="tab-pane {% if form.initial.module_type %}active{% endif %}" id="module-type" role="tabpanel" aria-labeledby="vm_tab">
          {% render_field form.module_type %}
        </div>
      </div>
    </div>
    <div class="field-group my-5">
      {% render_field form.tags %}
    </div>
    <div class="field-group my-5">
      <div class="row mb-2">
        <h5 class="offset-sm-3">Lifecycle Details</h5>
      </div>
      {% render_field form.notice_url label="Notice URL" %}
      {% render_field form.end_of_sale label="End of Sale" %}
      {% render_field form.end_of_maintenance label="End of SW Maintenance" %}
      {% render_field form.end_of_security label="End of Security Vulnerability" %}
      {% render_field form.last_contract_attach label="End of Contract Attach" %}
      {% render_field form.last_contract_renewal label="End of Contract Renewal" %}
      {% render_field form.end_of_support label="End of Support" %}
    </div>
    <div class="field-group my-5">
      <div class="row mb-2">
        <h5 class="offset-sm-3">Business Planning</h5>
      </div>
      {% render_field form.migration_pid label="Migration PID" %}
      {% render_field form.migration_pid_cost label="Migration PID Cost Est." %}
      {% render_field form.migration_pid_cost_currency label="Migration PID Cost Currency" %}
      {% render_field form.migration_calc_key label="Calculate Years from" %}
    </div>
    <div class="field-group my-5">
      {% render_field form.comments %}
    </div>
    {% if form.custom_fields %}
    <div class="field-group my-5">
        <div class="row mb-2">
          <h5 class="offset-sm-3">Custom Fields</h5>
        </div>
        {% render_custom_fields form %}
    </div>
    {% endif %}
{% endblock %}

netbox_lcm/templates/netbox_lcm/hardwarelifecycleplan.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load lcm_filters %}
{% load perms %}
{% load plugins %}
{% load tabs %}

{% block content %}
  <div class="row">
    <div class="col col-12 col-xl-6">
      <div class="card">
        <h2 class="card-header">Device Details</h2>
        <table class="table table-hover attr-table">
          <tr>
            <th>Manufacturer</th>
            <td>{{ object.device.device_type.manufacturer.name|linkify }}</td>
          </tr>
          <tr>
            <th>Device Type</th>
            <td>{{ object.device.device_type|linkify }}</td>
          </tr>
          <tr>
            <th>Serial Number</th>
            <td>{{ object.device.serial|linkify }}</td>
          </tr>
          <tr>
            <th>Description</th>
            <td>{{ object.device.description }}</td>
          </tr>
        </table>
      </div>
      <div class="card">
        <h2 class="card-header">Plan Details</h2>
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Plan Type</th>
            <td>{{ object.get_plan_type_display }}</td>
          </tr>
          <tr>
            <th scope="row">Status</th>
            <td>{{ object.get_status_display }}</td>
          </tr>
          <tr>
            <th scope="row">Resourced by</th>
            <td>{{ object.get_resourcing_type_display|capfirst }}</td>
          </tr>
          <tr>
            <th scope="row">Planned Completion Date</th>
            <td><span {{ object.completion_by|date_badge_class }}>{{ object.completion_by }}</span></td>
          </tr>
        </table>
      </div>
      {% plugin_left_page object %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/comments.html' %}
      {% plugin_right_page object %}
    </div>
  </div>
  <div class="row">
    <div class="col col-md-12">
      {% plugin_full_width_page object %}
    </div>
  </div>
{% endblock %}

netbox_lcm/templates/netbox_lcm/hardwarelifecycleplan_edit.html
{% extends 'generic/object_edit.html' %}
{% load form_helpers %}
{% load i18n %}
{% load static %}

{% block form %}
    <div class="field-group my-5">
      <div class="row mb-2">
        <h5 class="offset-sm-3">Device Assignment</h5>
      </div>
      <div class="tab-content p-0 border-0">
        <div class="tab-pane {% if not form.initial.circuit %}active{% endif %}" id="device" role="tabpanel">
          {% render_field form.device %}
        </div>
    </div>

    <div class="field-group my-5">      
      <div class="row mb-2">
        <h5 class="offset-sm-3">Hardware Lifecycle Plan Detail</h5>
      </div>
      {% render_field form.plan_type label="Plan Type" %}
      {% render_field form.status label="Plan Status" %}
      {% render_field form.resourcing_type label="Plan resourced by" %}
      {% render_field form.completion_by label="Planned Completion Date" %}
    </div>
    <div class="field-group my-5">
      {% render_field form.tags %}
      {% render_field form.comments %}
    </div>
    {% if form.custom_fields %}
    <div class="field-group my-5">
        <div class="row mb-2">
          <h5 class="offset-sm-3">Custom Fields</h5>
        </div>
        {% render_custom_fields form %}
    </div>
    {% endif %}
{% endblock %}

netbox_lcm/templates/netbox_lcm/license.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load tabs %}

{% block content %}
  <div class="row">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">License</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th>Manufacturer</th>
              <td>{{ object.manufacturer|linkify }}</td>
            </tr>
            <tr>
              <th>Name</th>
              <td>{{ object.name }}</td>
            </tr>
            <tr>
              <th>Description</th>
              <td>{{ object.description }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% plugin_left_page object %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/related_objects.html' %}
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/comments.html' %}
      {% plugin_right_page object %}
    </div>
  </div>
  <div class="row">
    <div class="col col-md-12">
      {% plugin_full_width_page object %}
    </div>
  </div>
{% endblock %}

netbox_lcm/templates/netbox_lcm/supportcontract.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load tabs %}

{% if perms.netbox_lcm.add_supportcontractassignment %}
  {% block extra_controls %}
    <a href="{% url 'plugins:netbox_lcm:supportcontractassignment_add' %}?contract={{ object.pk }}"
      class="btn btn-primary">
      <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add Assignment
    </a>
  {% endblock %}
{% endif %}

{% block content %}
  <div class="row">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Contract</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th>Manufacturer</th>
              <td>{{ object.manufacturer|linkify|placeholder }}</td>
            </tr>
            <tr>
              <th>Vendor</th>
              <td>{{ object.vendor|linkify|placeholder }}</td>
            </tr>
            <tr>
              <th>Contract ID</th>
              <td>{{ object.contract_id }}</td>
            </tr>
            <tr>
              <th>Description</th>
              <td>{{ object.description }}</td>
            </tr>
          </table>
        </div>
      </div>
      <div class="card">
        <h5 class="card-header">Dates</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th>Start</th>
              <td>{{ object.start }}</td>
            </tr>
            <tr>
              <th>Last renewal</th>
              <td>{{ object.renewal }}</td>
            </tr>
            <tr>
              <th>End</th>
              <td>{{ object.end }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% plugin_left_page object %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/related_objects.html' %}
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/comments.html' %}
      {% plugin_right_page object %}
    </div>
  </div>
  <div class="row">
    <div class="col col-md-12">
      {% plugin_full_width_page object %}
    </div>
  </div>
{% endblock %}